### ISSUE TITLE
Blocking is not working

### ISSUE THREAD

**Issue by joki0924** [Snoothy/UCR#62]
This project is really awesome, but it seems there is an error or bug like following one. 
I tried changing BlockingEnabled value to True on Settings.xml file on the same directory as Core_Interception.dll file.
But key blocking was not working.
Please help me.
Thanks.

**Comment by joki0924** [comment]
I already installed Interception library and individual keyboards are working perfectly.

**Comment by evilC** [comment]
Yeah, there have been reported problems with the latest version.  
We have a new version in the works with support for enabling or disabling blocking on a per-input basis, but we need to add the GUI to support it, hopefully we can get it out soon.  
If it is going to be longer, I will try and look and pushing out a fix in the meantime

**Comment by joki0924** [comment]
Thanks for your reply and support.

**Comment by evilC** [comment]
I just made a test build of a new version that may solve your problems.  
https://ci.appveyor.com/api/buildjobs/7xy05re34e43neto/artifacts/artifacts%2FUCR_v0.6.1-feature.long-to-short%2B282.zip  
If it doesn't fix things for you, feel free to drop by the [Discord Channel](https://discord.gg/bQDRE5F) and I can maybe help you out

**Comment by joki0924** [comment]
Wow thanks for your great support!

**Comment by joki0924** [comment]
Happy new year 2019.

**Comment by joki0924** [comment]
I checked your new version and it works perfectly on my local.
The blocking feature is really cool~
Thanks a lot.
Hope your great success.
I will keep my fingers crossed for you!🍀🍀🍀

**Comment by 94d33m** [comment]
In the new version theres no 'invert' option in button to axis, so how do i emulate xbox LeftStick/RightStick to the right and left / up / down?

**Comment by evilC** [comment]
Fixed in UCR 0.7.0

**Comment by rjborba** [comment]
Hi @evilC . Congratulations for your software. Really amazing and exactly what I was looking for.
I'm a developer. Looking forward to contribute.

But for now I'm just reporting a bug. Seems like blocking still not working on Release v0.9.0 Alpha even with BlockingEnable on:

`<?xml version="1.0" encoding="utf-8" ?>
<Settings>
  <Setting>
    <Name>BlockingEnabled</Name>
    <Value>True</Value>
  </Setting>
  <Setting>
	
    <Name>PollRate</Name>
    <Value>10</Value>
  </Setting>
  <Setting>
	
    <Name>StrokeOnThread</Name>
    <Value>false</Value>
  </Setting>
</Settings>`


Any tips?
Thanks in advance :D

**Comment by Flightofbird** [comment]
Yes I'm having the same issue, I can't get blocking to work in v0.9.0 My workaround was to install v0.7.0 and it works fine

**Comment by rjborba** [comment]
In my case there was no bug. There is another switch to turn on/off blocking for each key.
I totally forgot to turn it on
